/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as EmbeddingImport } from './routes/embedding'
import { Route as AboutImport } from './routes/about'
import { Route as IndexImport } from './routes/index'
import { Route as AskRepoImport } from './routes/ask/$repo'

// Create/Update Routes

const EmbeddingRoute = EmbeddingImport.update({
  id: '/embedding',
  path: '/embedding',
  getParentRoute: () => rootRoute,
} as any)

const AboutRoute = AboutImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const AskRepoRoute = AskRepoImport.update({
  id: '/ask/$repo',
  path: '/ask/$repo',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutImport
      parentRoute: typeof rootRoute
    }
    '/embedding': {
      id: '/embedding'
      path: '/embedding'
      fullPath: '/embedding'
      preLoaderRoute: typeof EmbeddingImport
      parentRoute: typeof rootRoute
    }
    '/ask/$repo': {
      id: '/ask/$repo'
      path: '/ask/$repo'
      fullPath: '/ask/$repo'
      preLoaderRoute: typeof AskRepoImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/embedding': typeof EmbeddingRoute
  '/ask/$repo': typeof AskRepoRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/embedding': typeof EmbeddingRoute
  '/ask/$repo': typeof AskRepoRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/embedding': typeof EmbeddingRoute
  '/ask/$repo': typeof AskRepoRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/about' | '/embedding' | '/ask/$repo'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/embedding' | '/ask/$repo'
  id: '__root__' | '/' | '/about' | '/embedding' | '/ask/$repo'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  EmbeddingRoute: typeof EmbeddingRoute
  AskRepoRoute: typeof AskRepoRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  EmbeddingRoute: EmbeddingRoute,
  AskRepoRoute: AskRepoRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/about",
        "/embedding",
        "/ask/$repo"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/about": {
      "filePath": "about.tsx"
    },
    "/embedding": {
      "filePath": "embedding.tsx"
    },
    "/ask/$repo": {
      "filePath": "ask/$repo.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
